name: MacOS Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_macOS:

    runs-on: macos-latest
    
    strategy:
      matrix:
        arch: ['arm', 'x86']

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Set up permissions
      run: chmod +x build-macOS_${{ matrix.arch }}.sh 

    - name: Build
      run: ./build-macOS_${{ matrix.arch }}.sh 

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: appdecrypt-macOS-${{ matrix.arch }}
        path: appdecrypt
        
  build_iOS:
    runs-on: macos-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Set up permissions
      run: chmod +x build-iOS.sh 

    - name: Build
      run: ./build-iOS.sh

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: appdecrypt-iOS
        path: appdecrypt
